#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef HAL_LOP_ENERGY_RECOVERY_ENABLED
#define HAL_LOP_ENERGY_RECOVERY_ENABLED 0
#endif

#ifndef AP_ENERGY_RECOVERY_ENABLED
#define AP_ENERGY_RECOVERY_ENABLED HAL_LOP_ENERGY_RECOVERY_ENABLED
#endif

#ifndef HAL_LOP_ENERGY_VOLT_PIN
#define HAL_LOP_ENERGY_VOLT_PIN -1
#endif

#ifndef HAL_LOP_ENERGY_CURR_PIN
#define HAL_LOP_ENERGY_CURR_PIN -1
#endif

#ifndef HAL_LOP_ENERGY_VOLT_SCALE
#define HAL_LOP_ENERGY_VOLT_SCALE 11.0f
#endif

#ifndef HAL_LOP_ENERGY_CURR_SCALE
#define HAL_LOP_ENERGY_CURR_SCALE 17.0f
#endif

#ifndef HAL_LOP_ENERGY_CUTOFF_PIN
#define HAL_LOP_ENERGY_CUTOFF_PIN -1
#endif

#ifndef HAL_LOP_ENERGY_CUTOFF_ACTIVE_HIGH
#define HAL_LOP_ENERGY_CUTOFF_ACTIVE_HIGH 1
#endif

#ifndef AP_LOP_EREC_ADC_FILTER_SIZE
#define AP_LOP_EREC_ADC_FILTER_SIZE 8
#endif

#ifndef AP_LOP_EREC_SCHED_HZ
#define AP_LOP_EREC_SCHED_HZ 5
#endif

#ifndef AP_LOP_EREC_SCHED_MAX_US
#define AP_LOP_EREC_SCHED_MAX_US 100
#endif

#ifndef AP_LOP_EREC_SCHED_PRIORITY
#define AP_LOP_EREC_SCHED_PRIORITY 254
#endif

#ifndef AP_LOP_EREC_LOGGING_ENABLED
#define AP_LOP_EREC_LOGGING_ENABLED AP_ENERGY_RECOVERY_ENABLED
#endif

#ifndef AP_LOP_EREC_SAFETY_RESPONSE_MS
#define AP_LOP_EREC_SAFETY_RESPONSE_MS 10
#endif
